### ISSUE TITLE
TARANTULA RS

### ISSUE THREAD

**Issue by jjrricardo** [lachusmadeti/Tarantula-RS#1]
Homers / tevo is sending the TARANTULA RS with MKS GEN L V1.0 cards could supply this firmware.

Here are some files provided by homers
https://drive.google.com/drive/folders/1G9QkEk4tSwV9xehqE_GB3AwNJe-4KsqZ?usp=sharing

**Comment by Helroyr** [comment]
Thank you very much !

**Comment by lachusmadeti** [comment]
Yes it's old firmware (Marlin 2.0) I got It before they released to the public and use as base for do mine, for MKS SGEN L and BTT SKR v1.3

Thanks for the comment!

**Comment by jjrricardo** [comment]
I can use this same mk sgen l firmware for my plate MKS GEN L V 1.0

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by lachusmadeti** [comment]
GEN L is 8 bits SGEN L is 32 bits, they are different board, it´s possible to adapt, I know a various units of RS with 8 bits boards, I search the builder info and try to make for it.
