### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by charlesdarwin76** [lachusmadeti/Tarantula-RS#2]
I m getting this error. I am not sure where it coming from but when verification process it appear.

#error "Oops! Make sure you have the LPC1768 environment selected in your IDE.
#error "You cannot set E0_AUTO_FAN_PIN equal to FAN_PIN.

Many Thanks

**Comment by lachusmadeti** [comment]
For the first error you need to define env_default= LPC1768 on platformio.ini. Change and try to compile again.
Which board it´s yours? BTT SKR v1.3 or MKS Sgen L v1.0?

Because first version of BTT SKR v1.3 I uploaded I was a fault pin definition, but I solved the same day.

Best regards.

**Comment by charlesdarwin76** [comment]
Hello Javier,
Thanks for your reply. I did change the text below but the same error I am
using MKS Sgen L v1.0 as per TTP/RS...

[platformio]
src_dir     = Marlin
build_dir   = .pioenvs
lib_dir     = .piolib
libdeps_dir = .piolibdeps
boards_dir  = buildroot/share/PlatformIO/boards
env_default = LPC1768

Regards,
Charles

**Comment by lachusmadeti** [comment]
Solved and added platformio.ini file.
